# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import base64
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from threading import Thread
import socket

from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(606, 10, 91, 31))
        self.comboBox.setObjectName("comboBox")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(480, 190, 221, 51))
        self.textEdit.setObjectName("textEdit")

        self.textEdit2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit2.setGeometry(QtCore.QRect(50, 450, 541, 191))
        self.textEdit2.setObjectName("textEdit2")

        self.textEdit3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit3.setGeometry(QtCore.QRect(50, 70, 381, 241))
        self.textEdit3.setObjectName("textEdit3")

        self.Button_pic = QtWidgets.QPushButton(self.centralwidget)
        self.Button_pic.setGeometry(QtCore.QRect(50, 360, 151, 41))
        self.Button_pic.setObjectName("Button_pic")

        self.Button_data = QtWidgets.QPushButton(self.centralwidget)
        self.Button_data.setGeometry(QtCore.QRect(270, 360, 141, 41))
        self.Button_data.setObjectName("Button_data")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 270, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.Button_send = QtWidgets.QPushButton(self.centralwidget)
        self.Button_send.setGeometry(QtCore.QRect(450, 270, 131, 41))
        self.Button_send.setObjectName("Button_send")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 26))
        self.menubar.setObjectName('menubar')
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName('menu')
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "在线聊天系统"))
        self.Button_pic.setText(_translate("MainWindow", "发送文件"))
        self.Button_data.setText(_translate("MainWindow", "发送文件夹"))
        self.Button_send.setText(_translate("MainWindow", "发送"))
        self.textEdit.setHtml(_translate("MainWindow", " "))
        self.pushButton.setText(_translate("MainWindow", "清除数据"))
        self.menu.setTitle(_translate("MainWindow", "聊天小工具"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mainwindow  = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
